// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/registry.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // Field 1: service name
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`                          // Field 2: IP:Port. e.g. "10.0.0.1:8080"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_proto_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_proto_registry_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterReq) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RegisterReq) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type RegisterResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Heartbeat interval. Defined on the server side
	Ttl           int64 `protobuf:"varint,1,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	mi := &file_proto_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_proto_registry_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResp) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type HeartbeatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"` // Composite Key: service_name + endpoint
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatReq) Reset() {
	*x = HeartbeatReq{}
	mi := &file_proto_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReq) ProtoMessage() {}

func (x *HeartbeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReq.ProtoReflect.Descriptor instead.
func (*HeartbeatReq) Descriptor() ([]byte, []int) {
	return file_proto_registry_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatReq) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *HeartbeatReq) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type DiscoverReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // which service I discover
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverReq) Reset() {
	*x = DiscoverReq{}
	mi := &file_proto_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverReq) ProtoMessage() {}

func (x *DiscoverReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverReq.ProtoReflect.Descriptor instead.
func (*DiscoverReq) Descriptor() ([]byte, []int) {
	return file_proto_registry_proto_rawDescGZIP(), []int{3}
}

func (x *DiscoverReq) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type DiscoverResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     []string               `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"` // slice or array: return all available IP:Port lists
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverResp) Reset() {
	*x = DiscoverResp{}
	mi := &file_proto_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverResp) ProtoMessage() {}

func (x *DiscoverResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverResp.ProtoReflect.Descriptor instead.
func (*DiscoverResp) Descriptor() ([]byte, []int) {
	return file_proto_registry_proto_rawDescGZIP(), []int{4}
}

func (x *DiscoverResp) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_registry_proto_rawDescGZIP(), []int{5}
}

var File_proto_registry_proto protoreflect.FileDescriptor

const file_proto_registry_proto_rawDesc = "" +
	"\n" +
	"\x14proto/registry.proto\x12\bregistry\"L\n" +
	"\vRegisterReq\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\" \n" +
	"\fRegisterResp\x12\x10\n" +
	"\x03ttl\x18\x01 \x01(\x03R\x03ttl\"M\n" +
	"\fHeartbeatReq\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\"0\n" +
	"\vDiscoverReq\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\",\n" +
	"\fDiscoverResp\x12\x1c\n" +
	"\tendpoints\x18\x01 \x03(\tR\tendpoints\"\a\n" +
	"\x05Empty2\xb6\x01\n" +
	"\bRegistry\x129\n" +
	"\bRegister\x12\x15.registry.RegisterReq\x1a\x16.registry.RegisterResp\x124\n" +
	"\tHeartbeat\x12\x16.registry.HeartbeatReq\x1a\x0f.registry.Empty\x129\n" +
	"\bDiscover\x12\x15.registry.DiscoverReq\x1a\x16.registry.DiscoverRespB\x1bZ\x19github.com/CTingy/go-service-registry/protob\x06proto3"

var (
	file_proto_registry_proto_rawDescOnce sync.Once
	file_proto_registry_proto_rawDescData []byte
)

func file_proto_registry_proto_rawDescGZIP() []byte {
	file_proto_registry_proto_rawDescOnce.Do(func() {
		file_proto_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_registry_proto_rawDesc), len(file_proto_registry_proto_rawDesc)))
	})
	return file_proto_registry_proto_rawDescData
}

var file_proto_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_registry_proto_goTypes = []any{
	(*RegisterReq)(nil),  // 0: registry.RegisterReq
	(*RegisterResp)(nil), // 1: registry.RegisterResp
	(*HeartbeatReq)(nil), // 2: registry.HeartbeatReq
	(*DiscoverReq)(nil),  // 3: registry.DiscoverReq
	(*DiscoverResp)(nil), // 4: registry.DiscoverResp
	(*Empty)(nil),        // 5: registry.Empty
}
var file_proto_registry_proto_depIdxs = []int32{
	0, // 0: registry.Registry.Register:input_type -> registry.RegisterReq
	2, // 1: registry.Registry.Heartbeat:input_type -> registry.HeartbeatReq
	3, // 2: registry.Registry.Discover:input_type -> registry.DiscoverReq
	1, // 3: registry.Registry.Register:output_type -> registry.RegisterResp
	5, // 4: registry.Registry.Heartbeat:output_type -> registry.Empty
	4, // 5: registry.Registry.Discover:output_type -> registry.DiscoverResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_registry_proto_init() }
func file_proto_registry_proto_init() {
	if File_proto_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_registry_proto_rawDesc), len(file_proto_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_registry_proto_goTypes,
		DependencyIndexes: file_proto_registry_proto_depIdxs,
		MessageInfos:      file_proto_registry_proto_msgTypes,
	}.Build()
	File_proto_registry_proto = out.File
	file_proto_registry_proto_goTypes = nil
	file_proto_registry_proto_depIdxs = nil
}
